In [1]:
import pandas as pd

df = pd.read_csv("messy_ecommerce - Sheet1.csv")

df.head()

,order_id,customer_name,email,product,category,price,quantity,order_date,shipping_status,country
0,ORD1000,NaN,test@gmail.com,Tablet,NaN,1136.18,2,11/6/2024,Shipped,usa
1,ORD1001,Maria Lopez,example@outlook.com,Phone,ELECTRONICS,168.35,4,1/2/2023,Delivered,USA
2,ORD1002,Timmy Pual,test@gmail.com,Phone,NaN,209.13,3,10/26/2023,Delivered,United States
3,ORD1003,Carlos Ruiz,user@yahoo.com,Keyboard,NaN,1373.69,1,12/2/2023,Canceled,Mexico
4,ORD1004,Amy Tims,example@outlook.com,Monitor,ELECTRONICS,468.47,5,11/17/2023,Shipped,United States

In [2]:
df.isnull().sum()

order_id            54
customer_name      443
email              562
product              0
category           513
price               96
quantity             0
order_date          68
shipping_status      0
country            432
dtype: int64

In [3]:
df['customer_name'] = df['customer_name'].fillna("Unknown")
df['email'] = df['email'].fillna("noemail@gmail.com")
df['category'] = df['category'].fillna("Unknown")
df['country'] = df['country'].fillna("Unknown")
df['price'] = df['price'].fillna(df['price'].median())

In [4]:
df.duplicated().sum()

np.int64(91)

In [5]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [6]:
df['country'].unique()

<StringArray>
['usa', 'USA', 'United States', 'Mexico', 'Unknown']
Length: 5, dtype: str

In [7]:
df['country'] = df['country'].str.strip().str.lower()

df['country'] = df['country'].replace({
    'usa': 'United States',
    'united states': 'United States',
    'mexico': 'Mexico'
})

df['country'].unique()

<StringArray>
['United States', 'Mexico', 'unknown']
Length: 3, dtype: str

In [8]:
df['category'].unique()

<StringArray>
['Unknown', 'ELECTRONICS', 'electronics', 'Electronics']
Length: 4, dtype: str

In [9]:
df['category'] = df['category'].str.strip().str.lower()

In [10]:
df['order_date'].unique()

<StringArray>
[ '11/6/2024',   '1/2/2023', '10/26/2023',  '12/2/2023', '11/17/2023',
  '4/16/2024',   '5/5/2023',  '7/29/2025',  '1/15/2025',   '9/2/2023',
 ...
  '1/17/2025', '11/18/2025',  '3/20/2024',  '4/12/2025',  '3/15/2023',
   '2/1/2025',  '2/20/2026',   '3/8/2025',  '9/19/2024',  '5/14/2024']
Length: 943, dtype: str

In [11]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

In [12]:
df.head(20)

,order_id,customer_name,email,product,category,price,quantity,order_date,shipping_status,country
0,ORD1000,Unknown,test@gmail.com,Tablet,unknown,1136.180,2,2024-11-06,Shipped,United States
1,ORD1001,Maria Lopez,example@outlook.com,Phone,electronics,168.350,4,2023-01-02,Delivered,United States
2,ORD1002,Timmy Pual,test@gmail.com,Phone,unknown,209.130,3,2023-10-26,Delivered,United States
3,ORD1003,Carlos Ruiz,user@yahoo.com,Keyboard,unknown,1373.690,1,2023-12-02,Canceled,Mexico
4,ORD1004,Amy Tims,example@outlook.com,Monitor,electronics,468.470,5,2023-11-17,Shipped,United States
5,ORD1005,Timmy Bob,example@outlook.com,Tablet,electronics,551.140,5,2024-04-16,Canceled,United States
6,ORD1006,John Doe,noemail@gmail.com,Keyboard,electronics,288.100,4,2023-05-05,Pending,United States
7,ORD1007,John Doe,noemail@gmail.com,Laptop,electronics,463.310,3,2025-07-29,Canceled,United States
8,ORD1008,Tim Gates,test@gmail.com,Monitor,electronics,364.820,3,2025-01-15,Pending,United States
9,ORD1009,John Doe,noemail@gmail.com,Tablet,unknown,764.425,4,2023-09-02,delivered,Mexico
10,ORD1010,Unknown,example@outlook.com,Laptop,electronics,825.780,2,2024-10-06,Pending,Mexico
11,ORD1011,Unknown,noemail@gmail.com,Phone,electronics,424.100,2,2023-09-21,Canceled,United States
12,ORD1012,Jenny Thomas,test@gmail.com,Keyboard,electronics,696.680,1,2026-01-14,Delivered,United States
13,ORD1013,Amber Garcia,test@gmail.com,Tablet,electronics,316.820,2,2023-08-25,Pending,United States
14,ORD1014,Joanna Anderson,test@gmail.com,Tablet,unknown,828.610,1,2024-02-25,Shipped,United States
15,ORD1015,Unknown,noemail@gmail.com,Phone,electronics,1247.670,5,2023-08-13,Delivered,Mexico
16,ORD1016,Joyce Thomas,example@outlook.com,Monitor,electronics,606.660,1,2023-06-10,Delivered,United States
17,ORD1017,Jennifer Cares,user@yahoo.com,Phone,electronics,764.425,3,2024-02-17,Pending,United States
18,ORD1018,Benny Anderson,test@gmail.com,Monitor,electronics,1084.680,3,2024-04-10,delivered,United States
19,ORD1019,Unknown,example@outlook.com,Phone,electronics,877.000,2,2024-03-16,Delivered,United States

In [13]:
df.to_csv("cleaned_ecommerce_data.csv", index=False)

In [14]:
%pip install sqlalchemy psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\Users\konde\AppData\Roaming\Python\Python314\site-packages (2.0.52)
Requirement already satisfied: psycopg2-binary in C:\Users\konde\AppData\Roaming\Python\Python314\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in C:\Users\konde\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\konde\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres"
password = "your_password"
host = "localhost"
port = "5432"
database = "ecommerce_project"

encoded_password = quote_plus(password)

engine = create_engine(
    f"postgresql+psycopg2://{username}:{encoded_password}@{host}:{port}/{database}"
)

In [17]:
with engine.connect() as connection:
    print("Connection successful!")

Connection successful!

In [18]:
df.to_sql(
    "cleaned_orders",
    engine,
    if_exists="append",
    index=False
)

9